### ISSUE TITLE
Perspectives of using DenoEx in Live Book

### ISSUE THREAD

**Issue by AdrielBento** [akoutmos/deno_ex#20]
First off, great job for making the library @akoutmos 💜 

Can you see any perspective of using DenoEx within Live Book? Does such a use case make sense, or am I going crazy?

Could this be a way for us to be able to take advantage of the benefits of the Live Book, but using another language?

**Comment by AdrielBento** [comment]
I accessed the examples folder and I think I have already been answered 😆. Thanks

**Comment by akoutmos** [comment]
> I accessed the examples folder and I think I have already been answered 😆. Thanks

If you think of any other cool Livebook examples, be sure to submit a PR 😉 .
